### ISSUE TITLE
[Windows][Step 4] Sign that do nothing, without message

### ISSUE THREAD

**Issue by lcaminon** [bitgreen/bitg-airdrop-verifier#2]
I did not really understood the disclaimer at the start of the tool, so maybe it's because of that (my wallet didn't have balance before 4 may)
But when I'm at step 4, when I click to the "Sign" button, nothing happen.
Precisely, the button become grey for something like 1 second and go back to green after that.
Can't click on "Next".
Nothing appear in my wallets directory.

**Comment by Nadro-J** [comment]
Hey, are you using Windows or Mac?

**Comment by lcaminon** [comment]
I'm using Windows

**Comment by Nadro-J** [comment]
Are you using a wallet that has a balance? Ignore the disclaimer at the start; 4th of May is just a place holder. It should also create a bitgreen.conf file in your block directory for the app to connect with but requires your wallet to be restarted for the config to take affect.

**Comment by lcaminon** [comment]
Ok, I didn't reproduce the problem, it was stuck at step 2.
But then I changed the directory of step 1 with the block directory and it worked !
